; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; デバイス共通設定
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified @ ^0.2.10                     ; M5Stackメインコントローラ向けデバイスドライバライブラリ
    tzapu/WiFiManager @ ^2.0.17                     ; WiFiManager
    ricmoo/QRCode @ ^0.0.1                          ; 画面描画用QRコードライブラリ
    bblanchon/ArduinoJson @ ^7.1.0                  ; JSONデータ解析、作成
    mikalhart/TinyGPSPlus                           ; GPSモジュール用ライブラリ（本プロジェクトではGPSモジュールは使用しない、ライブラリが提供する関数のみ使用）

; M5Stack Basic用
[env:m5stack-core-esp32]
board = m5stack-core-esp32

; M5Stack Core用
[env:m5Stack-cores3]
board = m5stack-cores3
; CoreS3に必要な専用フラグ
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1                    ; シリアルモニタの表示フラグ
    -D BOARD_HAS_PSRAM                              ; PSRAMの有効化
