; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; デバイス共通設定
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    m5stack/M5Unified @ ^0.2.10                     ; M5Stackメインコントローラ向けデバイスドライバライブラリ
    bblanchon/ArduinoJson @ ^7.1.0                  ; JSONデータ解析、作成

; M5Stack Basic用
[env:m5stack-core-esp32]
board = m5stack-core-esp32
board_build.partitions = no_ota.csv                 ; OTA不使用のためアプリ・LittleFS領域を拡張。具体的な配分は同名ファイル（no_ota.csv）を参照
                                                    ; 適用後は必ず再書き込みが必要（パーティション構成変更のため）

; M5Stack Core用
[env:m5Stack-cores3]
board = m5stack-cores3
board_build.partitions = default_16MB.csv           ; 16MBチップだがPlatformIOのデフォルトは4MB機種向け構成のため、
                                                    ; 明示的に16MB向け構成を指定してアプリ領域を拡張する
                                                    ; 適用後は必ず再書き込みが必要（パーティション構成変更のため）
; CoreS3に必要な専用フラグ
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1                    ; シリアルモニタの表示フラグ
    -D BOARD_HAS_PSRAM                              ; PSRAMの有効化
